// Code generated by tygo. DO NOT EDIT.

//////////
// source: api_status.go

export interface SatisfactoryApiStatus {
  running: boolean;
  pingMs: number /* int */;
}

//////////
// source: auth.go

/**
 * LoginRequest represents the request body for authentication.
 */
export interface LoginRequest {
  password: string;
}
/**
 * LoginResponse represents the response after successful authentication.
 */
export interface LoginResponse {
  success: boolean;
  usedDefaultPassword: boolean;
}
/**
 * AuthStatusResponse represents the current authentication status.
 */
export interface AuthStatusResponse {
  authenticated: boolean;
  usedDefaultPassword?: boolean;
}
/**
 * ChangePasswordRequest represents the request to change the access key.
 */
export interface ChangePasswordRequest {
  currentPassword: string;
  newPassword: string;
}
/**
 * ChangePasswordResponse represents the response after password change.
 */
export interface ChangePasswordResponse {
  success: boolean;
  message?: string;
}
/**
 * LogoutResponse represents the response after logout.
 */
export interface LogoutResponse {
  success: boolean;
}

//////////
// source: belt.go

export interface Belt {
  id: string;
  name: string;
  location0: Location;
  location1: Location;
  connected0: boolean;
  connected1: boolean;
  splineData: Location[];
  length: number /* float64 */;
  itemsPerMinute: number /* float64 */;
}
export interface Belts {
  belts: Belt[];
  splitterMergers: SplitterMerger[];
}

//////////
// source: cable.go

export interface Cable {
  id: string;
  name: string;
  location0: Location;
  location1: Location;
  connected0: boolean;
  connected1: boolean;
  length: number /* float64 */;
}

//////////
// source: circuit.go

export interface CircuitConsumption {
  total: number /* float64 */;
  max: number /* float64 */;
}
export interface CircuitProduction {
  total: number /* float64 */;
}
export interface CircuitCapacity {
  total: number /* float64 */;
}
export interface CircuitBattery {
  percentage: number /* float64 */;
  capacity: number /* float64 */;
  differential: number /* float64 */;
  untilFull: number /* float64 */; // parsed from 00:00:00 to float64
  untilEmpty: number /* float64 */; // parsed from 00:00:00 to float64
}
export interface Circuit {
  id: string;
  fuseTriggered: boolean;
  consumption: CircuitConsumption;
  production: CircuitProduction;
  capacity: CircuitCapacity;
  battery: CircuitBattery;
}

//////////
// source: circuit_ids.go

export interface CircuitIDs {
  circuitId: number /* int */;
  circuitGroupId?: number /* int */;
}

//////////
// source: drone.go

export type DroneStatus = string;
export const DroneStatusIdle: DroneStatus = 'idle';
export const DroneStatusFlying: DroneStatus = 'flying';
export const DroneStatusDocking: DroneStatus = 'docking';
export interface Drone extends Location, CircuitIDs {
  name: string;
  speed: number /* float64 */;
  status: DroneStatus;
  home: DroneStation;
  paired?: DroneStation;
  destination?: DroneStation;
  circuitId: number /* int */;
  circuitGroupId: number /* int */;
}

//////////
// source: drone_station.go

export interface DroneStation extends Location, CircuitIDs {
  name: string;
  fuel?: Fuel;
  boundingBox: BoundingBox;
  incomingRate: number /* float64 */; // Average incoming items/minute
  outgoingRate: number /* float64 */; // Average outgoing items/minute
  inputInventory: ItemStats[]; // Items being received
  outputInventory: ItemStats[]; // Items being sent
}

//////////
// source: dto.go

export type SatisfactoryApiStatusDTO = SatisfactoryApiStatus;
export type CircuitDTO = Circuit;
export type DroneDTO = Drone;
export type DroneStationDTO = DroneStation;
export type ExplorerDTO = Explorer;
export type FactoryStatsDTO = FactoryStats;
export type GeneratorStatsDTO = GeneratorStats;
export type MachineDTO = Machine;
export type MachineProdStatsDTO = MachineProdStats;
export type PlayerDTO = Player;
export type ProdStatsDTO = ProdStats;
export type SinkStatsDTO = SinkStats;
export type TractorDTO = Tractor;
export type TrainDTO = Train;
export type TrainStationDTO = TrainStation;
export type TruckDTO = Truck;
export type VehiclePathDTO = VehiclePath;
export type StateDTO = State;
export type BeltDTO = Belt;
export type PipeDTO = Pipe;
export type PipeJunctionDTO = PipeJunction;
export type TrainRailDTO = TrainRail;
export type SplitterMergerDTO = SplitterMerger;
export type CableDTO = Cable;
export type VehiclesDTO = Vehicles;
export type VehicleStationsDTO = VehicleStations;
export type SchematicDTO = Schematic;
export type StorageDTO = Storage;
export type SpaceElevatorDTO = SpaceElevator;
export type HubDTO = Hub;
export type RadarTowerDTO = RadarTower;
export interface DroneSetupDTO {
  drones: DroneDTO[];
  droneStations: DroneStationDTO[];
}
export interface TrainSetupDTO {
  trains: TrainDTO[];
  trainStations: TrainStationDTO[];
}
export interface BeltsDTO {
  belts: BeltDTO[];
  splitterMerges: SplitterMergerDTO[];
}
export interface PipesDTO {
  pipes: PipeDTO[];
  pipeJunctions: PipeJunctionDTO[];
}

//////////
// source: error.go

export interface BindingError {
  validationErrors: { [key: string]: string[] };
}
export interface ErrorResponse {
  errors: ApiError[];
}
export interface ApiError {
  code: string;
  msg: string;
}
/**
 * SatisfactoryApiError represents an error during communication with Satisfactory API.
 */
export interface SatisfactoryApiError {
  Message: string;
}

//////////
// source: explorer.go

export type ExplorerStatus = string;
export const ExplorerStatusSelfDriving: ExplorerStatus = 'selfDriving';
export const ExplorerStatusManualDriving: ExplorerStatus = 'manualDriving';
export const ExplorerStatusParked: ExplorerStatus = 'parked';
export const ExplorerStatusUnknown: ExplorerStatus = 'unknown';
export interface Explorer extends Location, CircuitIDs {
  id: string;
  name: string;
  speed: number /* float64 */;
  status: ExplorerStatus;
  fuel?: Fuel;
  inventory: ItemStats[];
}

//////////
// source: factory_stats.go

export interface MachineEfficiency {
  machinesOperating: number /* int */;
  machinesIdle: number /* int */;
  machinesPaused: number /* int */;
  machinesUnconfigured: number /* int */;
  machinesUnknown: number /* int */;
}
export interface FactoryStats {
  totalMachines: number /* int */;
  efficiency: MachineEfficiency;
}

//////////
// source: fuel.go

export interface Fuel {
  Name: string;
  amount: number /* float64 */;
}

//////////
// source: generator_stats.go

export type PowerType = string;
export const PowerTypeBiomass: PowerType = 'biomass';
export const PowerTypeCoal: PowerType = 'coal';
export const PowerTypeFuel: PowerType = 'fuel';
export const PowerTypeGeothermal: PowerType = 'geothermal';
export const PowerTypeNuclear: PowerType = 'nuclear';
export const PowerTypeUnknown: PowerType = 'unknown';
export interface PowerSource {
  count: number /* int */;
  totalProduction: number /* float64 */;
}
export interface GeneratorStats {
  sources: { [key: PowerType]: PowerSource };
}

//////////
// source: hub.go

/**
 * HubMilestoneCost represents an item required for milestone completion
 */
export interface HubMilestoneCost {
  name: string;
  amount: number /* float64 */; // Amount submitted so far
  remainingCost: number /* float64 */; // How much left to submit
  totalCost: number /* float64 */; // Total required
}
/**
 * HubMilestone represents the active milestone at the HUB
 */
export interface HubMilestone {
  name: string;
  techTier: number /* int */;
  type: string; // "Milestone" or "No Milestone Selected"
  cost: HubMilestoneCost[];
}
/**
 * Hub represents the HUB Terminal
 */
export interface Hub extends Location {
  id: string;
  name: string;
  hasActiveMilestone: boolean;
  activeMilestone?: HubMilestone;
  shipDocked: boolean; // Is ship currently docked?
  shipReturnTime?: number /* int64 */; // Unix timestamp (ms) when ship returns, null if docked
  boundingBox: BoundingBox;
}

//////////
// source: hypertube.go

export interface Hypertube {
  id: string;
  location0: Location;
  location1: Location;
  splineData: Location[];
  boundingBox: BoundingBox;
}
export interface HypertubeEntrance extends Location {
  id: string;
  boundingBox: BoundingBox;
  powerInfo: PowerInfo;
}
export interface Hypertubes {
  hypertubes: Hypertube[];
  hypertubeEntrances: HypertubeEntrance[];
}

//////////
// source: item_stats.go

export interface ItemStats {
  name: string;
  count: number /* float64 */;
}

//////////
// source: location.go

export interface Location {
  x: number /* float64 */;
  y: number /* float64 */;
  z: number /* float64 */;
  rotation: number /* float64 */;
}
export interface BoundingBox {
  min: Location;
  max: Location;
}

//////////
// source: machine.go

export type MachineType = string;
export const MachineTypeAssembler: MachineType = 'assembler';
export const MachineTypeConstructor: MachineType = 'constructor';
export const MachineTypeFoundry: MachineType = 'foundry';
export const MachineTypeManufacturer: MachineType = 'manufacturer';
export const MachineTypeRefinery: MachineType = 'refinery';
export const MachineTypeSmelter: MachineType = 'smelter';
export const MachineTypeBlender: MachineType = 'blender';
export const MachineTypePackager: MachineType = 'packager';
export const MachineTypeParticleAccelerator: MachineType = 'particleAccelerator';
export const MachineTypeMiner: MachineType = 'miner';
export const MachineTypeOilExtractor: MachineType = 'oilExtractor';
export const MachineTypeWaterExtractor: MachineType = 'waterExtractor';
export const MachineTypeBiomassBurner: MachineType = 'biomassBurner';
export const MachineTypeCoalGenerator: MachineType = 'coalGenerator';
export const MachineTypeFuelGenerator: MachineType = 'fuelGenerator';
export const MachineTypeGeothermalGenerator: MachineType = 'geothermalGenerator';
export const MachineTypeNuclearPowerPlant: MachineType = 'nuclearPowerPlant';
export type MachineCategory = string;
export const MachineCategoryFactory: MachineCategory = 'factory';
export const MachineCategoryExtractor: MachineCategory = 'extractor';
export const MachineCategoryGenerator: MachineCategory = 'generator';
export type MachineStatus = string;
export const MachineStatusOperating: MachineStatus = 'operating';
export const MachineStatusIdle: MachineStatus = 'idle';
export const MachineStatusPaused: MachineStatus = 'paused';
export const MachineStatusUnconfigured: MachineStatus = 'unconfigured';
export const MachineStatusUnknown: MachineStatus = 'unknown';
export interface MachineProdStats {
  name: string;
  stored: number /* float64 */;
  current: number /* float64 */;
  max: number /* float64 */;
  efficiency: number /* float64 */;
}
export interface Machine extends Location, CircuitIDs {
  type: MachineType;
  status: MachineStatus;
  category: MachineCategory;
  productivity: number /* float64 */; // 0-1
  input: MachineProdStats[];
  output: MachineProdStats[];
  boundingBox: BoundingBox;
}

//////////
// source: nodes.go

/**
 * NodeInfo represents information about a single API instance
 * tygo:alias object
 */
export interface NodeInfo {
  instanceId: string; // This instance's unique ID
  isThisInstance: boolean; // True if this is the current instance
  status: string; // Node status: "online", "initializing", or "offline"
  ownedSessions: SessionLease[]; // Sessions owned by this instance
}
/**
 * SessionLease represents lease information for a single session
 * tygo:alias object
 */
export interface SessionLease {
  sessionId: string; // Session ID
  sessionName: string; // Human-readable session name
  ownerId: string; // Instance that owns this lease
  preferredOwnerId: string; // Preferred owner per rendezvous hashing
  state: string; // "owned", "other", "uncertain", "unknown"
  acquiredAt: string; // When lease was acquired (zero if not owned)
  lastRenewedAt: string; // When lease was last renewed (zero if not owned)
  uncertainSince: string; // When lease became uncertain (zero if not uncertain)
}
/**
 * NodesResponse is the response for GET /v1/nodes
 * tygo:alias object
 */
export interface NodesResponse {
  thisInstanceId: string; // ID of this instance
  liveNodes: NodeInfo[]; // All live instances with their owned sessions
  timestamp: string; // When this snapshot was taken
}

//////////
// source: pipe.go

export interface Pipe {
  id: string;
  name: string;
  location0: Location;
  location1: Location;
  connected0: boolean;
  connected1: boolean;
  splineData: Location[];
  length: number /* float64 */;
  itemsPerMinute: number /* float64 */;
}
export interface Pipes {
  pipes: Pipe[];
  pipeJunctions: PipeJunction[];
}

//////////
// source: pipe_junction.go

export interface PipeJunction extends Location {
  id: string;
  name: string;
}

//////////
// source: player.go

export interface Player extends Location {
  id: string;
  name: string;
  health: number /* float64 */;
  items: ItemStats[];
}

//////////
// source: power_info.go

export interface PowerInfo {
  circuitId: number /* int */;
  circuitGroupId: number /* int */;
  powerConsumed: number /* float64 */;
  maxPowerConsumed: number /* float64 */;
}

//////////
// source: prod_stats.go

export interface ItemProdStats extends ItemStats {
  producedPerMinute: number /* float64 */;
  maxProducePerMinute: number /* float64 */;
  produceEfficiency: number /* float64 */;
  consumedPerMinute: number /* float64 */;
  maxConsumePerMinute: number /* float64 */;
  consumeEfficiency: number /* float64 */;
  cloudCount: number /* float64 */;
  minable: boolean;
}
export interface ProdStats {
  minableProducedPerMinute: number /* float64 */;
  minableConsumedPerMinute: number /* float64 */;
  itemsProducedPerMinute: number /* float64 */;
  itemsConsumedPerMinute: number /* float64 */;
  items: ItemProdStats[];
}

//////////
// source: radar_tower.go

export type ResourceNodePurity = string;
export const ResourceNodePurityImpure: ResourceNodePurity = 'Impure';
export const ResourceNodePurityNormal: ResourceNodePurity = 'Normal';
export const ResourceNodePurityPure: ResourceNodePurity = 'Pure';
export type ResourceType = string;
export const ResourceTypeIronOre: ResourceType = 'Iron Ore';
export const ResourceTypeCopperOre: ResourceType = 'Copper Ore';
export const ResourceTypeLimestone: ResourceType = 'Limestone';
export const ResourceTypeCoal: ResourceType = 'Coal';
export const ResourceTypeSAM: ResourceType = 'SAM';
export const ResourceTypeSulfur: ResourceType = 'Sulfur';
export const ResourceTypeCateriumOre: ResourceType = 'Caterium Ore';
export const ResourceTypeBauxite: ResourceType = 'Bauxite';
export const ResourceTypeRawQuartz: ResourceType = 'Raw Quartz';
export const ResourceTypeUranium: ResourceType = 'Uranium';
export const ResourceTypeCrudeOil: ResourceType = 'Crude Oil';
export const ResourceTypeGeyser: ResourceType = 'Geyser';
export const ResourceTypeNitrogenGas: ResourceType = 'Nitrogen Gas';
/**
 * NodeType represents the deposit classification
 */
export type NodeType = string;
export const NodeTypeNode: NodeType = 'Node';
export const NodeTypeGeyser: NodeType = 'Geyser';
export const NodeTypeFrackingCore: NodeType = 'Fracking Core';
export const NodeTypeFrackingSatellite: NodeType = 'Fracking Satellite';
export type FaunaType = string;
export const FaunaTypeLizardDoggo: FaunaType = 'Lizard Doggo';
export const FaunaTypeFluffyTailedHog: FaunaType = 'Fluffy-Tailed Hog';
export const FaunaTypeSpitter: FaunaType = 'Spitter';
export const FaunaTypeStinger: FaunaType = 'Stinger';
export const FaunaTypeFlyingCrab: FaunaType = 'Flying Crab';
export const FaunaTypeNonFlyingBird: FaunaType = 'Non-flying Bird';
export const FaunaTypeSpaceGiraffe: FaunaType = 'Space Giraffe-Tick-Penguin-Whale Thing';
export const FaunaTypeSporeFlower: FaunaType = 'Spore Flower';
export const FaunaTypeLeafBug: FaunaType = 'Leaf Bug';
export const FaunaTypeGrassSprite: FaunaType = 'Grass Sprite';
export const FaunaTypeCaveBat: FaunaType = 'Cave Bat';
export const FaunaTypeGiantFlyingManta: FaunaType = 'Giant Flying Manta';
export const FaunaTypeLakeShark: FaunaType = 'Lake Shark';
export const FaunaTypeWalker: FaunaType = 'Walker';
export type FloraType = string;
export const FloraTypeTree: FloraType = 'Tree';
export const FloraTypeLeaves: FloraType = 'Leaves';
export const FloraTypeFlowerPetals: FloraType = 'Flower Petals';
export const FloraTypeBaconAgaric: FloraType = 'Bacon Agaric';
export const FloraTypePaleberry: FloraType = 'Paleberry';
export const FloraTypeBerylNut: FloraType = 'Beryl Nut';
export const FloraTypeMycelia: FloraType = 'Mycelia';
export const FloraTypeVineLadder: FloraType = 'Vines';
export const FloraTypeBlueCapMushroom: FloraType = 'Blue Cap Mushroom';
export const FloraTypePinkJellyfish: FloraType = 'Pink Jellyfish';
export type SignalType = string;
export const SignalTypeSomersloop: SignalType = 'Somersloop';
export const SignalTypeMercerSphere: SignalType = 'Mercer Sphere';
export const SignalTypeBluePowerSlug: SignalType = 'Blue Power Slug';
export const SignalTypeYellowPowerSlug: SignalType = 'Yellow Power Slug';
export const SignalTypePurplePowerSlug: SignalType = 'Purple Power Slug';
export const SignalTypeHardDrive: SignalType = 'Hard Drive';
export interface ResourceNode extends Location {
  id: string;
  name: string;
  className: string;
  purity: ResourceNodePurity;
  resourceForm: string;
  resourceType: ResourceType;
  nodeType: NodeType;
  exploited: boolean;
}
export interface ScannedFauna {
  name: FaunaType;
  className: string;
  amount: number /* int */;
}
export interface ScannedFlora {
  name: FloraType;
  className: string;
  amount: number /* int */;
}
export interface ScannedSignal {
  name: SignalType;
  className: string;
  amount: number /* int */;
}
export interface RadarTower extends Location {
  id: string;
  revealRadius: number /* float64 */;
  nodes: ResourceNode[];
  fauna: ScannedFauna[];
  flora: ScannedFlora[];
  signal: ScannedSignal[];
  boundingBox: BoundingBox;
}

//////////
// source: satisfactory_event.go

export type SatisfactoryEventType = string;
export const SatisfactoryEventApiStatus: SatisfactoryEventType = 'satisfactoryApiCheck';
export const SatisfactoryEventCircuits: SatisfactoryEventType = 'circuits';
export const SatisfactoryEventFactoryStats: SatisfactoryEventType = 'factoryStats';
export const SatisfactoryEventProdStats: SatisfactoryEventType = 'prodStats';
export const SatisfactoryEventSinkStats: SatisfactoryEventType = 'sinkStats';
export const SatisfactoryEventPlayers: SatisfactoryEventType = 'players';
export const SatisfactoryEventGeneratorStats: SatisfactoryEventType = 'generatorStats';
export const SatisfactoryEventVehicles: SatisfactoryEventType = 'vehicles';
export const SatisfactoryEventVehicleStations: SatisfactoryEventType = 'vehicleStations';
export const SatisfactoryEventSessionUpdate: SatisfactoryEventType = 'sessionUpdate';
export const SatisfactoryEventBelts: SatisfactoryEventType = 'belts';
export const SatisfactoryEventPipes: SatisfactoryEventType = 'pipes';
export const SatisfactoryEventTrainRails: SatisfactoryEventType = 'trainRails';
export const SatisfactoryEventCables: SatisfactoryEventType = 'cables';
export const SatisfactoryEventStorages: SatisfactoryEventType = 'storages';
export const SatisfactoryEventMachines: SatisfactoryEventType = 'machines';
export const SatisfactoryEventTractors: SatisfactoryEventType = 'tractors';
export const SatisfactoryEventExplorers: SatisfactoryEventType = 'explorers';
export const SatisfactoryEventVehiclePaths: SatisfactoryEventType = 'vehiclePaths';
export const SatisfactoryEventSpaceElevator: SatisfactoryEventType = 'spaceElevator';
export const SatisfactoryEventHub: SatisfactoryEventType = 'hub';
export const SatisfactoryEventRadarTowers: SatisfactoryEventType = 'radarTowers';
export const SatisfactoryEventResourceNodes: SatisfactoryEventType = 'resourceNodes';
export const SatisfactoryEventHypertubes: SatisfactoryEventType = 'hypertubes';
export const SatisfactoryEventSchematics: SatisfactoryEventType = 'schematics';
export const SatisfactoryEventKey: string = 'satisfactory_events';
export interface SatisfactoryEvent {
  type: SatisfactoryEventType;
  data: any;
}
export interface SseSatisfactoryEvent extends SatisfactoryEvent {
  clientId: number /* int64 */;
}

//////////
// source: schematic.go

export interface SchematicCost {
  name: string;
  amount: number /* float64 */;
  totalCost: number /* float64 */;
}
export interface Schematic {
  id: string;
  name: string;
  tier: number /* int */;
  type: string;
  purchased: boolean;
  locked: boolean;
  lockedPhase: boolean;
  cost: SchematicCost[];
}

//////////
// source: session.go

/**
 * SessionStage represents the initialization stage of a session
 */
export type SessionStage = string;
export const SessionStageInit: SessionStage = 'init';
export const SessionStageReady: SessionStage = 'ready';
/**
 * Session represents a Satisfactory server connection target
 */
export interface Session {
  id: string; // UUID
  name: string; // User-provided display name
  address: string; // IP:port (e.g., "192.168.1.100:8080")
  sessionName: string; // From getSessionInfo API
  isMock: boolean; // True for mock session
  isOnline: boolean; // Current connection status
  isPaused: boolean; // True if polling is paused by user
  isDisconnected: boolean; // True if session has failed to connect multiple times
  createdAt: string;
}
/**
 * SessionInfoRaw represents the raw response from Satisfactory's getSessionInfo endpoint (PascalCase)
 */
export interface SessionInfoRaw {
  SessionName: string;
  IsPaused: boolean;
  DayLength: number /* int */;
  NightLength: number /* int */;
  PassedDays: number /* int */;
  NumberOfDaysSinceLastDeath: number /* int */;
  Hours: number /* int */;
  Minutes: number /* int */;
  Seconds: number /* float64 */;
  IsDay: boolean;
  TotalPlayDuration: number /* int */;
  TotalPlayDurationText: string;
}
/**
 * SessionInfo is the normalized DTO sent to the frontend (camelCase)
 */
export interface SessionInfo {
  sessionName: string;
  isPaused: boolean;
  dayLength: number /* int */;
  nightLength: number /* int */;
  passedDays: number /* int */;
  numberOfDaysSinceLastDeath: number /* int */;
  hours: number /* int */;
  minutes: number /* int */;
  seconds: number /* float64 */;
  isDay: boolean;
  totalPlayDuration: number /* int */;
  totalPlayDurationText: string;
}
/**
 * CreateSessionRequest is the request body for creating a new session
 */
export interface CreateSessionRequest {
  name: string;
  address: string; // Required for non-mock sessions
  isMock: boolean;
}
/**
 * UpdateSessionRequest is the request body for updating a session (all fields optional)
 */
export interface UpdateSessionRequest {
  name?: string;
  isPaused?: boolean;
  address?: string;
}
/**
 * SessionDTO is the data transfer object for Session with computed fields
 */
export interface SessionDTO {
  id: string;
  name: string;
  address: string;
  sessionName: string;
  isMock: boolean;
  isOnline: boolean;
  isPaused: boolean;
  isDisconnected: boolean; // True if session is in disconnected state
  createdAt: string;
  stage: SessionStage;
}

//////////
// source: settings.go
/*
Package models provides the data models for the Satisfactory Dashboard API.
*/

/**
 * LogLevel represents valid log levels
 */
export type LogLevel = string;
export const LogLevelTrace: LogLevel = 'Trace';
export const LogLevelDebug: LogLevel = 'Debug';
export const LogLevelInfo: LogLevel = 'Info';
export const LogLevelWarning: LogLevel = 'Warning';
export const LogLevelError: LogLevel = 'Error';
/**
 * Settings represents global application settings
 */
export interface Settings {
  logLevel: LogLevel; // Current log level
}
/**
 * SettingsChange represents a change to settings
 */
export interface SettingsChange {
  field: string; // e.g., "logLevel"
  oldValue: any; // Previous value
  newValue: any; // New value
}
/**
 * SettingsChangedEvent is published to Redis pub/sub when settings change
 */
export interface SettingsChangedEvent {
  settings: Settings; // Full new settings
  changes: SettingsChange[]; // List of what changed
}

//////////
// source: sink_stats.go

export interface SinkStats {
  totalPoints: number /* float64 */;
  coupons: number /* int */;
  nextCouponProgress: number /* float64 */;
  pointsPerMinute: number /* float64 */;
}

//////////
// source: space_elevator.go

export interface SpaceElevatorPhaseObjective {
  name: string;
  amount: number /* float64 */;
  totalCost: number /* float64 */;
}
export interface SpaceElevator extends Location {
  id: string;
  name: string;
  boundingBox: BoundingBox;
  currentPhase: SpaceElevatorPhaseObjective[];
  fullyUpgraded: boolean;
  upgradeReady: boolean;
}

//////////
// source: splitter_merger.go

export type SplitterMergerType = string;
export const SplitterMergerTypeConveyorMerger: SplitterMergerType = 'Conveyor Merger';
export const SplitterMergerTypeConveyorSplitter: SplitterMergerType = 'Conveyor Splitter';
export const SplitterMergerTypeProgrammableSplitter: SplitterMergerType = 'Programmable Splitter';
export const SplitterMergerTypeSmartSplitter: SplitterMergerType = 'Smart Splitter';
export interface SplitterMerger extends Location {
  id: string;
  type: SplitterMergerType;
  boundingBox: BoundingBox;
}

//////////
// source: state.go

export interface State {
  satisfactoryApiStatus: SatisfactoryApiStatus;
  factoryStats: FactoryStats;
  prodStats: ProdStats;
  generatorStats: GeneratorStats;
  sinkStats: SinkStats;
  circuits: Circuit[];
  players: Player[];
  drones: Drone[];
  trains: Train[];
  trainStations: TrainStation[];
  droneStations: DroneStation[];
  belts: Belt[];
  pipes: Pipe[];
  pipeJunctions: PipeJunction[];
  trainRails: TrainRail[];
  splitterMergers: SplitterMerger[];
  hypertubes: Hypertube[];
  hypertubeEntrances: HypertubeEntrance[];
  cables: Cable[];
  storages: Storage[];
  machines: Machine[];
  tractors: Tractor[];
  explorers: Explorer[];
  vehiclePaths: VehiclePath[];
  spaceElevator?: SpaceElevator;
  hub?: Hub;
  radarTowers: RadarTower[];
  resourceNodes: ResourceNode[];
  schematics: Schematic[];
}

//////////
// source: storage.go

export type StorageType = string;
export const StorageTypeBlueprintStorageBox: StorageType = 'Blueprint Storage Box';
export const StorageTypeDimensionalDepotUploader: StorageType = 'Dimensional Depot Uploader';
export const StorageTypeIndustrialStorageContainer: StorageType = 'Industrial Storage Container';
export const StorageTypePersonalStorageBox: StorageType = 'Personal Storage Box';
export const StorageTypeStorageContainer: StorageType = 'Storage Container';
export interface Storage extends Location {
  id: string;
  type: StorageType;
  inventory: ItemStats[];
  boundingBox: BoundingBox;
}

//////////
// source: tractor.go

export type TractorStatus = string;
export const TractorStatusSelfDriving: TractorStatus = 'selfDriving';
export const TractorStatusManualDriving: TractorStatus = 'manualDriving';
export const TractorStatusParked: TractorStatus = 'parked';
export const TractorStatusUnknown: TractorStatus = 'unknown';
export interface Tractor extends Location, CircuitIDs {
  id: string;
  name: string;
  speed: number /* float64 */;
  status: TractorStatus;
  fuel?: Fuel;
  inventory: ItemStats[];
}

//////////
// source: train.go

export type TrainType = string;
export const TrainTypeFreight: TrainType = 'freight';
export const TrainTypeLocomotive: TrainType = 'locomotive';
export type TrainStatus = string;
export const TrainStatusSelfDriving: TrainStatus = 'selfDriving';
export const TrainStatusManualDriving: TrainStatus = 'manualDriving';
export const TrainStatusParked: TrainStatus = 'parked';
export const TrainStatusDocking: TrainStatus = 'docking';
export const TrainStatusDerailed: TrainStatus = 'derailed';
export const TrainStatusUnknown: TrainStatus = 'unknown';
export interface TrainVehicle {
  type: TrainType;
  capacity: number /* float64 */;
  inventory: ItemStats[];
}
export interface TrainTimetableEntry {
  station: string;
}
export interface Train extends Location, CircuitIDs {
  id: string;
  name: string;
  speed: number /* float64 */;
  status: TrainStatus;
  powerConsumption: number /* float64 */;
  vehicles: TrainVehicle[];
  timetable: TrainTimetableEntry[];
  timetableIndex: number /* int */;
}

//////////
// source: train_rail.go

export type TrainRailType = string;
export const TrainRailTypeRailway: TrainRailType = 'Railway';
export interface TrainRail {
  id: string;
  type: TrainRailType;
  location0: Location;
  location1: Location;
  connected0: boolean;
  connected1: boolean;
  splineData: Location[];
  length: number /* float64 */;
}

//////////
// source: train_station.go

export type TrainStationPlatformType = string;
export const TrainStationPlatformTypeFreight: TrainStationPlatformType = 'freight';
export const TrainStationPlatformTypeFluidFreight: TrainStationPlatformType = 'fluidFreight';
export type TrainStationPlatformMode = string;
export const TrainStationPlatformModeImport: TrainStationPlatformMode = 'import';
export const TrainStationPlatformModeExport: TrainStationPlatformMode = 'export';
export type TrainStationPlatformStatus = string;
export const TrainStationPlatformStatusIdle: TrainStationPlatformStatus = 'idle';
export const TrainStationPlatformStatusDocking: TrainStationPlatformStatus = 'docking';
export interface TrainStationPlatform extends Location {
  id: string;
  type: TrainStationPlatformType;
  mode: TrainStationPlatformMode;
  status: TrainStationPlatformStatus;
  boundingBox: BoundingBox;
  inventory: ItemStats[];
  transferRate: number /* float64 */; // Solid items rate
  inflowRate: number /* float64 */; // Fluid incoming rate
  outflowRate: number /* float64 */; // Fluid outgoing rate
}
export interface TrainStation extends Location, CircuitIDs {
  name: string;
  boundingBox: BoundingBox;
  platforms: TrainStationPlatform[];
}

//////////
// source: truck.go

export type TruckStatus = string;
export const TruckStatusSelfDriving: TruckStatus = 'selfDriving';
export const TruckStatusManualDriving: TruckStatus = 'manualDriving';
export const TruckStatusParked: TruckStatus = 'parked';
export const TruckStatusUnknown: TruckStatus = 'unknown';
export interface Truck extends Location, CircuitIDs {
  id: string;
  name: string;
  speed: number /* float64 */;
  status: TruckStatus;
  fuel?: Fuel;
  inventory: ItemStats[];
}

//////////
// source: truck_station.go

export interface TruckStation extends Location, CircuitIDs {
  name: string;
  boundingBox: BoundingBox;
  transferRate: number /* float64 */; // Current transfer rate
  maxTransferRate: number /* float64 */; // Max stacks/sec for all vehicles
  inventory: ItemStats[]; // Station inventory
  circuitId: number /* int */;
}

//////////
// source: vehicle_path.go

export type VehiclePathType = string;
export const VehiclePathTypeExplorer: VehiclePathType = 'Explorer';
export const VehiclePathTypeFactoryCart: VehiclePathType = 'Factory Cart';
export const VehiclePathTypeTruck: VehiclePathType = 'Truck';
export const VehiclePathTypeTractor: VehiclePathType = 'Tractor';
export interface VehiclePath {
  name: string;
  vehicleType: VehiclePathType;
  pathLength: number /* float64 */; // in meters
  vertices: Location[];
}

//////////
// source: vehicles.go

export interface Vehicles {
  trains: Train[];
  drones: Drone[];
  trucks: Truck[];
  tractors: Tractor[];
  explorers: Explorer[];
}
export interface VehicleStations {
  trainStations: TrainStation[];
  droneStations: DroneStation[];
  truckStations: TruckStation[];
}
