openapi: 3.0.3
info:
  title: Data History API
  description: API endpoints for historical data retrieval
  version: 1.0.0

paths:
  /v1/sessions/{sessionId}/history/{dataType}:
    get:
      summary: Get historical data for a session
      description: |
        Retrieves historical data points for the specified data type.
        Data is returned in ascending order by game-time ID.
        Use the `since` parameter for incremental fetching.
      operationId: getHistory
      tags:
        - History
      parameters:
        - name: sessionId
          in: path
          required: true
          description: Session UUID
          schema:
            type: string
            format: uuid
            example: "abc-123-def-456"
        - name: dataType
          in: path
          required: true
          description: Type of data to retrieve history for
          schema:
            type: string
            enum:
              - circuits
              - generatorStats
              - prodStats
              - factoryStats
              - sinkStats
        - name: saveName
          in: query
          required: false
          description: Save name to query. Defaults to current save if omitted.
          schema:
            type: string
            example: "MySaveGame"
        - name: since
          in: query
          required: false
          description: |
            Only return data points with gameTimeId greater than this value.
            Use 0 to get all available history.
          schema:
            type: integer
            format: int64
            minimum: 0
            default: 0
            example: 3600
        - name: limit
          in: query
          required: false
          description: Maximum number of data points to return
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            default: 100
            example: 100
      responses:
        '200':
          description: Historical data retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HistoryChunk'
        '400':
          description: Invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                invalidDataType:
                  value:
                    message: "Invalid data type: players is not a history-enabled type"
                invalidSince:
                  value:
                    message: "Invalid since parameter: must be a non-negative integer"
        '404':
          description: Session not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: "Session not found"

  /v1/sessions/{sessionId}/history:
    get:
      summary: List available save names with history
      description: Returns all save names that have historical data for this session
      operationId: listHistorySaves
      tags:
        - History
      parameters:
        - name: sessionId
          in: path
          required: true
          description: Session UUID
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of save names with history
          content:
            application/json:
              schema:
                type: object
                properties:
                  saveNames:
                    type: array
                    items:
                      type: string
                    example: ["MySaveGame", "AnotherSave", "TestWorld"]
                  currentSave:
                    type: string
                    description: Currently active save name
                    example: "MySaveGame"
        '404':
          description: Session not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    HistoryChunk:
      type: object
      required:
        - dataType
        - saveName
        - latestId
        - points
      properties:
        dataType:
          type: string
          description: The data type of this history chunk
          enum:
            - circuits
            - generatorStats
            - prodStats
            - factoryStats
            - sinkStats
          example: "prodStats"
        saveName:
          type: string
          description: The save name these points belong to
          example: "MySaveGame"
        latestId:
          type: integer
          format: int64
          description: |
            Highest gameTimeId in this chunk.
            Use this as the `since` parameter for subsequent requests.
          example: 7200
        points:
          type: array
          description: Array of data points, ordered by gameTimeId ascending
          items:
            $ref: '#/components/schemas/DataPoint'

    DataPoint:
      type: object
      required:
        - gameTimeId
        - data
      properties:
        gameTimeId:
          type: integer
          format: int64
          description: Game time in seconds when this data was captured
          example: 3600
        data:
          type: object
          description: |
            The actual data payload. Structure depends on dataType:
            - circuits: Array of Circuit objects
            - generatorStats: GeneratorStats object
            - prodStats: ProdStats object
            - factoryStats: FactoryStats object
            - sinkStats: SinkStats object

    SatisfactoryEvent:
      type: object
      description: SSE event payload (extended with gameTimeId)
      required:
        - type
        - data
      properties:
        type:
          type: string
          description: Event type identifier
          example: "prodStats"
        data:
          type: object
          description: Event payload
        gameTimeId:
          type: integer
          format: int64
          description: |
            Game time when event was captured.
            0 for non-history event types.
            Clients should ignore events where gameTimeId <= lastKnownId.
          example: 3604

    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Human-readable error message
          example: "Session not found"
