# OpenAPI 3.0 Contract: Authentication API
# Feature: 001-access-key-auth
# Date: 2026-01-10

openapi: 3.0.3
info:
  title: Satisfactory Dashboard Authentication API
  version: 1.0.0
  description: Access key authentication endpoints for the Satisfactory Dashboard

paths:
  /v1/auth/login:
    post:
      summary: Authenticate with access key
      description: |
        Exchange the dashboard access key (password) for an access token.
        The token is returned as an HTTP-only cookie.
        Rate limited to 5 attempts per minute per IP.
      operationId: login
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Authentication successful
          headers:
            Set-Cookie:
              description: HTTP-only cookie containing access token
              schema:
                type: string
                example: sd_access_token=abc123...; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /v1/auth/logout:
    post:
      summary: Invalidate access token
      description: |
        Invalidate the current access token and clear the session cookie.
        Requires authentication.
      operationId: logout
      tags:
        - Authentication
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Logout successful
          headers:
            Set-Cookie:
              description: Cleared cookie
              schema:
                type: string
                example: sd_access_token=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogoutResponse'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /v1/auth/status:
    get:
      summary: Check authentication status
      description: |
        Check if the current request is authenticated.
        This endpoint does not require authentication (always returns a response).
        Used by frontend to determine initial auth state.
      operationId: getAuthStatus
      tags:
        - Authentication
      responses:
        '200':
          description: Authentication status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthStatusResponse'

  /v1/auth/change-password:
    post:
      summary: Change the access key
      description: |
        Change the dashboard access key (password).
        Requires current password verification.
        Requires authentication.
      operationId: changePassword
      tags:
        - Authentication
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
      responses:
        '200':
          description: Password changed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChangePasswordResponse'
        '400':
          description: Invalid request (missing fields)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Not authenticated or current password incorrect
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sd_access_token
      description: HTTP-only cookie containing access token

  schemas:
    LoginRequest:
      type: object
      required:
        - password
      properties:
        password:
          type: string
          description: The dashboard access key
          example: my-secret-password

    LoginResponse:
      type: object
      required:
        - success
        - usedDefaultPassword
      properties:
        success:
          type: boolean
          description: Whether authentication was successful
          example: true
        usedDefaultPassword:
          type: boolean
          description: Whether the default password "change-me" was used
          example: false

    AuthStatusResponse:
      type: object
      required:
        - authenticated
      properties:
        authenticated:
          type: boolean
          description: Whether the current request is authenticated
          example: true
        usedDefaultPassword:
          type: boolean
          description: Whether the session was created with the default password (only present if authenticated)
          example: false

    ChangePasswordRequest:
      type: object
      required:
        - currentPassword
        - newPassword
      properties:
        currentPassword:
          type: string
          description: The current access key for verification
          example: old-password
        newPassword:
          type: string
          minLength: 1
          description: The new access key
          example: new-secure-password

    ChangePasswordResponse:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean
          description: Whether the password was changed successfully
          example: true
        message:
          type: string
          description: Optional message (e.g., confirmation or error details)
          example: Password changed successfully

    LogoutResponse:
      type: object
      required:
        - success
      properties:
        success:
          type: boolean
          description: Whether logout was successful
          example: true

    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Error message
          example: Invalid password
