export const abbreviations = new Map<string, string>(
  Object.entries({
    // Ores and Raw Materials
    cpr: 'Copper Ore',
    cop: 'Copper Ore',
    irn: 'Iron Ore',
    iro: 'Iron Ore',
    cnc: 'Concrete',
    con: 'Concrete',
    lms: 'Limestone',
    lim: 'Limestone',
    oil: 'Crude Oil',
    cru: 'Crude Oil',
    wtr: 'Water',
    h2o: 'Water',
    wat: 'Water',
    sul: 'Sulfur',
    sfr: 'Sulfur',
    cat: 'Caterium Ore',
    ctm: 'Caterium Ore',
    qrz: 'Raw Quartz',
    qtz: 'Raw Quartz',
    qua: 'Raw Quartz',
    bxt: 'Bauxite',
    bau: 'Bauxite',
    sua: 'Sulfuric Acid',
    sfa: 'Sulfuric Acid',
    nit: 'Nitrogen',
    ntr: 'Nitrogen',
    col: 'Coal',
    coa: 'Coal',

    // Processed Materials
    plt: 'Plastic',
    pls: 'Plastic',
    pla: 'Plastic',
    rbr: 'Rubber',
    rub: 'Rubber',
    stl: 'Steel',
    ste: 'Steel',
    alu: 'Aluminum',
    alm: 'Aluminum',
    slt: 'Silica',
    sil: 'Silica',
    aas: 'Alclad Aluminum Sheet',
    cas: 'Aluminum Casing',

    // Parts and Equipment
    mtr: 'Motor',
    mot: 'Motor',
    str: 'Stator',
    sta: 'Stator',
    rpl: 'Rotor',
    rot: 'Rotor',
    cbl: 'Cable',
    cab: 'Cable',
    wir: 'Wire',
    wrb: 'Wire Bundle',
    scr: 'Screw',
    sce: 'Screw',
    sbm: 'Steel Beam',
    stb: 'Steel Beam',
    bea: 'Steel Beam',
    spb: 'Steel Pipe',
    pip: 'Steel Pipe',
    imb: 'Iron Beam',
    ipe: 'Iron Pipe',
    mod: 'Modular Frame',
    mdf: 'Modular Frame',
    hmf: 'Heavy Modular Frame',

    // Electronics
    ccb: 'Circuit Board',
    cic: 'Circuit Board',
    sup: 'Supercomputer',
    scp: 'Supercomputer',
    cpt: 'Computer',
    cmp: 'Computer',
    enc: 'Encased Industrial Beam',
    eib: 'Encased Industrial Beam',

    // Fluids and Gases
    fsr: 'Fuel Rod',
    ful: 'Fuel',
    ngs: 'Nitrogen Gas',
    bat: 'Battery',
    bty: 'Battery',
    hoc: 'Heavy Oil Canister',
    hor: 'Heavy Oil Residue',

    // Miscellaneous
    qrs: 'Quartz Crystal',
    crc: 'Crystal',
  })
);
