openapi: 3.0.3
info:
  title: Satisfactory Dashboard - Schematics API
  description: API endpoint for fetching schematic/milestone unlock status
  version: 1.0.0

paths:
  /v1/schematics:
    get:
      summary: List all milestones
      description: |
        Returns all milestone schematics with their purchase status.
        Only includes schematics where Type === "Milestone".
        Used to determine which features are unlocked in the dashboard.
      operationId: listSchematics
      tags:
        - Schematics
      parameters:
        - name: session_id
          in: query
          required: true
          description: Session identifier for multi-session support
          schema:
            type: string
            example: "abc123"
      responses:
        '200':
          description: List of milestone schematics
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Schematic'
              example:
                - id: "Schematic_6-3_C"
                  name: "Monorail Train Technology"
                  tier: 6
                  type: "Milestone"
                  purchased: true
                - id: "Schematic_7-4_C"
                  name: "Aeronautical Engineering"
                  tier: 8
                  type: "Milestone"
                  purchased: false
        '400':
          description: Missing or invalid session_id parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "session_id query parameter is required"
        '425':
          description: Session not ready (still initializing)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Session is not ready yet"

components:
  schemas:
    Schematic:
      type: object
      description: A game milestone/schematic with unlock status
      required:
        - id
        - name
        - tier
        - type
        - purchased
      properties:
        id:
          type: string
          description: Unique schematic identifier from game
          example: "Schematic_6-3_C"
        name:
          type: string
          description: Display name of the milestone
          example: "Monorail Train Technology"
        tier:
          type: integer
          minimum: 0
          maximum: 9
          description: Technology tier (0-9)
          example: 6
        type:
          type: string
          description: Schematic type (always "Milestone" for this endpoint)
          example: "Milestone"
        purchased:
          type: boolean
          description: Whether the milestone has been unlocked in game
          example: true

    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
          example: "session_id query parameter is required"
